apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelab-deployment
  labels:
    app: kubelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubelab
  template:
    metadata:
      labels:
        app: kubelab
    spec:
      containers:
        - name: kubelab-pod
          image: timlinsenmayer/kubelab-insights:latest
          ports:
            - containerPort: 3000
          env:
            - name: SECRET-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: my-configmap