apiVersion: v1
kind: Service
metadata:
  name: kubelab-service
spec:
  type: NodePort
  selector:
    app: kubelab
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000